development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rorapp
  pool: 5
  username: root
  password: '1whisky&soda?YES!'
  host: localhost
  #socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rorapp_test
  pool: 5
  username: root
  password: '1whisky&soda?YES!'
  host: localhost
  #socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rorapp
  pool: 5
  username: root

